### ISSUE TITLE
Object instance function throws error

### ISSUE THREAD

**Issue by robcatch** [whitfin/expansion-js#1]
If a constructor is defined in the following format, the instance function throws an error.

```
var Currency = function(amount, currency){
    this.amount = amount;
    this.currency = currency || typeof(userData) !== "undefined" && userData.currency || 'GBP';
};
var c = new Currency();
c.instance();
TypeError: this.constructor.toString(...).match(...) is null
```

This is because the value of `constructor.toString()` does not contain the name.

```
c.constructor.toString()
"function(amount, currency){
    this.amount = amount;
    this.currency = currency || typeof(userData) !== "undefined" && userData.currency || 'GBP';
}"
```

**Comment by whitfin** [comment]
Yeah it's not possible when associating a var with an anonymous constructor. The question is how anonymous should be represented; should it just return Object? Or null?

**Comment by robcatch** [comment]
I think Object would be better

**Comment by whitfin** [comment]
This will be handled in https://github.com/iwhitfield/expansion-js/commit/198d527f73f61a33a72517fe42dd0ef71b7eb0fd - anonymous functions will default to "". This replicates the behaviour taken by ECMAScript 6's Function.name.
