### ISSUE TITLE
How do I change the timeout in it.each?

### ISSUE THREAD

**Issue by ncorison** [whitfin/expansion-js#2]
The standard way to change the timeout in an "it" statement is with:

this.timeout(msec);

This doesn't work on "it.each"; is there a way? The only information provided is for a static implementation and uses the default of 2000 ms in its example. I need to change the delay for a dynamic implementation.

**Comment by whitfin** [comment]
@ncorison I think you left this on the wrong repo, but feel free to file an issue on it.each and I'll look into it!

**Comment by ncorison** [comment]
You may be right, and the issue was resolved some time ago, but thanks!

Norman

**Comment by whitfin** [comment]
@ncorison I just pushed an update to it.each here: https://github.com/iwhitfield/it.each/releases and it's also available on npm. It allows you to control the mocha context from inside your function, so you can set timeouts and slows appropriately.
